[tool.poetry]
name = "jenkins-101"
version = "0.1.0"
description = ""
authors = ["Panagiotis Kapsalis <kapsali29@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
